apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-feed-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-feed
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
